sudo: required
services:
    - docker

before_install: 
    - docker build -t uks/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true uks/react-test npm test

after_success:
    - docker build -t agacsakal/multi-client ./client 
    - docker build -t agacsakal/multi-nginx ./nginx 
    - docker build -t agacsakal/multi-server ./server
    - docker build -t agacsakal/multi-worker ./worker
    #Log in to Docker CLI
    # Gerçek şifreyi Travis içinde bu etiketlerle
    # environment içine kaydettik.
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push to Docker Hub
    - docker push agacsakal/multi-client 
    - docker push agacsakal/multi-nginx
    - docker push agacsakal/multi-server
    - docker push agacsakal/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: multi-docker
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-1-896321501291"
    bucket_path: "docker-multi"
    on:
        branch: master
        

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


 
